### PR TITLE
#162170704 Integrate Coveralls code coverage service

### PR DESCRIPTION
**Pull request by akhilome**
#### What does this PR do?

Setup test coverage reporting with coveralls

#### Description of Task to be completed?

- install nyc's reporter and the coveralls npm package
- add coverage reporting badge to readme
- modify test script to use nyc's lcov reporter
- add a coverage script which runs travis build passes

#### How should this be manually tested?

Check the README.md file for the coveralls badge

#### Any background context you want to provide?

N/A

#### What are the relevant pivotal tracker stories?

[#162170704](https://www.pivotaltracker.com/story/show/162170704)

#### Screenshots (if appropriate)

screen shot 2018-11-28 at 7 05 08 am

#### Questions:

N/A

### CODE REVIEW

**Comment by omokaro-faith** [comment]
@akhilome Fix conflicts

**Comment by akhilome** [comment]
@omokaro-faith I'm waiting on #8 to be merged to `staging` so that I can resolve all conflicts which will, inevitably, arise at once.

**Comment by omokaro-faith** [comment]
@akhilome Request done.

**Comment by omokaro-faith** [comment]
@akhilome Fix Conflicts.

**Comment by akhilome** [comment]
> @akhilome Fix Conflicts.

On it.

**Comment by akhilome** [comment]
@omokaro-faith New conflicts fixed.

**Pull request merged**
