### PR TITLE
#163144010 Fix hound violation warnings

### PR DESCRIPTION
**Pull request by akhilome**
#### What does this PR do?

fixes hound ci violation issues

#### Description of Task to be completed?

N/A

#### How should this be manually tested?

N/A

#### Any background context you want to provide?

N/A

#### What are the relevant pivotal tracker stories? (If applicable)

[#163144010](https://www.pivotaltracker.com/story/show/163144010)

#### Screenshots (If applicable)

N/A

#### Questions:

N/A

### CODE REVIEW

**Review by okoroemeka — APPROVED** [review]

**Review by oluwajuwon — APPROVED** [review]
LGTM! 👍

**Review by frostyblok — APPROVED** [review]
Good job!

**Review by marcdomain — APPROVED** [review]
LGTM!

**Comment by Johnsonojo** [comment]
Good Job!

**Pull request merged**
